indent_style = "Visual"
use_small_heuristics = "Off"
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
brace_style = "PreferSameLine"
empty_item_single_line = true
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = false
max_width = 180
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
space_before_colon = false
struct_field_align_threshold = 20
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 8
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
wrap_comments = false
comment_width = 300
match_arm_blocks = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
color = "Always"
unstable_features = true
edition = "2018"
version = "Two"
normalize_doc_attributes = true

